spring.application.name=demo
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:postgres:}
spring.datasource.password=${DB_PASSWORD:}
spring.threads.virtual.enabled=true

# Auto create and auto update lines
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

